Operator version 3.0.2
oracle/weblogic-kubernetes-operator pull request #1912
Opened 2020-09-11 22:43 UTC by rjeberhard

We are planning to release another set of bug fixes.

The following PR's were selected based on customer impact and severity:
* #1867 
* #1869 
* #1872 
* #1878 
* #1879 

Additionally, the following PR's were required because one or more of the PR's in the above list depended on these changes:
* #1827 
* #1832

2020-09-11 23:44 UTC, tbarnes-us commented
Can you please also consider https://github.com/oracle/weblogic-kubernetes-operator/pull/1842?  It's just a FAQ update and customers seem to need the info -- I think another customer ran into this just this week.

2020-09-16 12:21 UTC, rjeberhard commented
Tests have passed: https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/1959/

2020-09-16 12:35 UTC, rosemarymarano approved these changes
From the doc perspective, LGTM.

2020-09-16 13:31 UTC, russgold commented
What is the process of adding bug fixes? It doesn't look as though you are cherry-picking commits merged into develop, as you've been squashing the PRs to single commits, and here you seem to be using the original commits on the branch. How will this affect merging future work from develop into master?

2020-09-16 13:34 UTC, rjeberhard commented
I cherry-picked the commits from the original PR's.

2020-09-16 13:35 UTC, rjeberhard commented
After we merge to master, I'll merge master back into develop to make sure that there are no conflicts (there shouldn't be).

2020-09-16 13:51 UTC, russgold commented
What is the advantage of doing that vs. cherry-picking the squashed commits?

2020-09-16 14:14 UTC, mriccell requested changes

2020-09-16 14:14 UTC, mriccell commented on docs-source/content/release-notes.md
> +| September 15, 2020 | v3.0.2 | no | This release contains several fixes, including improvements to log rotation and a fix that avoids unnecessarily updating the domain status. |
Can we list the fixes that went into 3.0.2 for user reference?

2020-09-16 15:59 UTC, mriccell approved these changes

2020-09-16 16:11 UTC, rosemarymarano approved these changes
One edit request/comment.

2020-09-16 16:11 UTC, rosemarymarano commented on docs-source/content/release-notes.md
>  | Date | Version | Introduces backward incompatibilities? | Changes |
Changes -> Change (I let this go before but it was a mistake. It should be singular, change, just like all the other headings are singular, Date, Version, Issue, and Description. The question mark after Introduces backward incompatibilities? is ok.) I looked at the Change log in the Hugo UI and it all looks fine, definitely good to go.

2020-09-16 17:40 UTC, merged