OWLS-84517: Scaling failed when setting Dedicated to true
oracle/weblogic-kubernetes-operator pull request #1921
Opened 2020-09-15 05:21 UTC by lennyphan

When namespace selection strategy is configured to be 'Dedicated', requests to the Operator's REST endpoint fail authentication.  Authentication checks were always cluster scoped.  The fix is for REST endpoint authentication to be namespace scoped when in 'Dedicated' namespace selection strategy,

2020-09-15 19:17 UTC, russgold requested changes
Other than the one oversight, this looks good.

2020-09-15 19:17 UTC, russgold commented on operator/src/test/java/oracle/kubernetes/operator/helpers/AuthenticationProxyTest.java
> +      System.out.println("AuthorizationProxyStub.check scope: " + scope);
It is bad practice to leave a println in your tests. I assume you needed this for debugging and forgot to remove it?

2020-09-15 20:12 UTC, hzhao-github commented
With the change, Scaling test passed in my local:

<09-15-2020 13:06:30> <INFO> <oracle.weblogic.kubernetes.extensions.IntegrationTestWatcher printHeader> <
+++++++++++++++++++++++++++++++++++++++++++++++++
Test PASSED testDedicatedModeSameNamespaceScale()
+++++++++++++++++++++++++++++++++++++++++++++++++
>
<09-15-2020 13:06:30> <INFO> <oracle.weblogic.kubernetes.extensions.IntegrationTestWatcher printHeader> <
----------------------------------------------------------------
Starting afterAll for oracle.weblogic.kubernetes.ItDedicatedMode
----------------------------------------------------------------

2020-09-15 21:03 UTC, alai8 approved these changes

2020-09-15 23:25 UTC, hzhao-github approved these changes

2020-09-15 23:25 UTC, hzhao-github commented
LGTM

2020-09-16 02:26 UTC, russgold approved these changes

2020-09-17 14:56 UTC, merged