Tanzu sample certification documentation
oracle/weblogic-kubernetes-operator pull request #2057
Opened 2020-11-17 18:45 UTC by sankarpn

Creating a sample for running operator on Tanzu Kubernetes grid. 
The sample uses model-in-image domain and metallb loadbalancer for accessing applications deployed in cluster.
Also has example to configure nginx for accessing admin console.

2020-11-17 20:50 UTC, rosemarymarano reviewed
Wow, quite a tome. It's basically very well written; you'll see mostly minor edits. However, I think the format (heading levels and such) need improvement. I would be glad to re-review it with that in mind, when all the other edits and input are completed; just let me know when it's done.

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> + - Image creation
This bulleted item is out of place because there is just one. I suggest that you remove it. (It's not needed.)

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +1. The JAVA_HOME environment variable must be set and must reference a valid JDK 8 or 11 installation.
JAVA_HOME -> `JAVA_HOME` (code font)

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +The archive top directory, named `wlsdeploy`, contains a directory named `applications`, which includes an ‘exploded’ sample JSP web application in the directory, myapp-v1. Three useful aspects to re
myapp-v1 -> `myapp-v1` (code font)

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +    - A `cluster-1` targeted ear application that’s located in the WDT archive ZIP file at `wlsdeploy/applications/myapp-v1`
ear  -> EAR

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +Creating the image with WIT
Creating the image with WIT -> Redundant, remove

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +If you are taking the JRF path through the sample, then remove --chown oracle:root from the imagetool.sh command below.
If you are taking the JRF path through the sample, -> I don't recall you describing anything about a JRF path through the sample

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +- Update WebLogic Kubernetes Operator to manage WebLogic domain namespace
Update WebLogic Kubernetes Operator -> Update the WebLogic Server Kubernetes Operator OR Update the operator (preferred)
manage WebLogic domain namespace -> manage the WebLogic domain namespace

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +  - Create a Secret containing your Model in Image runtime encryption password:
password:
If the next three bulleted items are sub-bulleted to this one, then they need to be indented further.

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +##### Upgrade operator
Upgrade operator -> Upgrade the operator

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +Upgrade operator to manage WebLogic domains in namespace `sample-domain1-ns`
Upgrade operator -> Upgrade the operator

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +Run the following kubectl commands to deploy the required secrets:
kubectl  -> `kubectl ` (code font)

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +Verify the WebLogic server pods are all running
WebLogic server -> WebLogic Server
running -> running:

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +##### Create loadbalancer
Create loadbalancer -> Create  load balancer

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +Create loadbalancer to access WebLogic server admin console and to access applications deployed in cluster.
Create loadbalancer -> Create a load balancer
to access WebLogic server admin console and to access applications deployed in cluster. -> to access the WebLogic Server Administration Console and applications deployed in the cluster.

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +Tanzu supports mettallb loadbalancer and nginx ingress for routing.
supports mettallb loadbalancer-> supports the MetalLB load balancer
nginx  -> NGINX

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +##### Install Metallb loadbalancer by running following commands.
Install Metallb loadbalancer -> Install the MetalLB load balancer

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +## deploy metallb loadbalancer
metallb loadbalancer -> MetalLB load balancer

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +##### Install Nginx
Nginx -> NGINX

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +##### Create ingress for admin console access
admin console access -> Administration Console access

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +##### Access admin console
admin console -> the Administration Console

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +Access admin console using loadbalancer ip (192.168.100.50)
Access admin console using loadbalancer ip (192.168.100.50) -> Access the Administration Console using the load balancer IP(`192.168.100.50`)

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +##### Access sample application
Access sample application -> Access the sample application

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +Welcome to WebLogic server 'managed-server1'!
WebLogic server -> WebLogic Server

2020-11-17 20:50 UTC, rosemarymarano commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +Welcome to WebLogic server 'managed-server2'!
WebLogic server -> WebLogic Server

2020-11-17 22:06 UTC, sankarpn reviewed
Thank you Rosemary for the thorough comments. Added the changes. But looks like I need create a PR to merge this changes to master instead of develop branch. I have created an another PR https://github.com/oracle/weblogic-kubernetes-operator/pull/2059  . Please review.

2020-11-18 20:48 UTC, mriccell requested changes

2020-11-18 20:48 UTC, mriccell commented on docs-source/content/samples/simple/tanzu-kubernetes-service/_index.md
> +After going through the steps, your WLS domain runs on an TKG Kubernetes cluster instance and you can manage your WLS domain by accessing the WebLogic Server Administration Console.
After going through the steps, your WLS domain  with domain source type of Model In Image runs on an TKG Kubernetes cluster instance.  Once the domain has been provisioned you can monitor it using the WebLogic Administration console.

2020-11-19 18:38 UTC, rjeberhard commented
This PR should be closed, correct? I'd like to have us work on the pull to master and then once that is committed, we will merge the same changes back to develop.

2020-11-19 19:32 UTC, sankarpn commented
> 
> 
> This PR should be closed, correct? I'd like to have us work on the pull to master and then once that is committed, we will merge the same changes back to develop.

Yes, this PR is replaced by https://github.com/oracle/weblogic-kubernetes-operator/pull/2059
Closing it.

2020-11-19 19:32 UTC, closed without merging