OWLS-86817, upgraded Monitoring Exporter  version to 1.3.0
oracle/weblogic-kubernetes-operator pull request #2121
Opened 2021-01-04 19:49 UTC by marinakog

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/3495

2021-01-04 19:52 UTC, markxnelson requested changes
update copyright year

2021-01-04 20:05 UTC, markxnelson reviewed
I think there should be a comma after 2021 - better check with @rjeberhard what rules you are using in the build

2021-01-04 20:11 UTC, rjeberhard commented
Answered in Slack... but for everyone's benefit the year value is always followed by a comma, so it's either "2021, " or "2020, 2021, "...

2021-01-04 20:31 UTC, anpanigr approved these changes

2021-01-05 17:54 UTC, rjeberhard approved these changes

2021-01-05 17:54 UTC, merged