Added test for sample script update_domain.sh ( wlst )
oracle/weblogic-kubernetes-operator pull request #2496
Opened 2021-08-09 15:17 UTC by hzhao-github

2021-08-10 21:12 UTC, anpanigr approved these changes

2021-08-11 19:37 UTC, bhavaniravichandran requested changes

2021-08-11 19:37 UTC, bhavaniravichandran commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java
> +public class ItWlsSamples {
Can you please remove the public from here and also all the test methods?
Ryan merged https://github.com/oracle/weblogic-kubernetes-operator/pull/2492 to make this change and you are overwriting this change.

2021-08-11 19:37 UTC, bhavaniravichandran commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java
> +  public void testSampleDomainInImage(String model) {
Remove public - see earlier comment.

2021-08-11 19:37 UTC, bhavaniravichandran commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java
> +  public void testSampleDomainInPv(String model) {
Remove public

2021-08-11 19:37 UTC, bhavaniravichandran commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java
> +  public void testServerLifecycleScripts() {
Remove public

2021-08-11 19:37 UTC, bhavaniravichandran commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java
> +  public void testServerLifecycleScriptsWithConstantReplicaCount() {
Remove public

2021-08-11 19:37 UTC, bhavaniravichandran commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java
> +  public void testClusterLifecycleScripts() {
Remove public

2021-08-11 19:37 UTC, bhavaniravichandran commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java
> +  public void testDomainLifecycleScripts() {
Remove public

2021-08-11 19:37 UTC, bhavaniravichandran commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java
> +  public void testTraefikIngressController() {
Remove public

2021-08-11 19:37 UTC, bhavaniravichandran commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java
> +  public void testVoyagerIngressController() {
Remove public

2021-08-11 19:37 UTC, bhavaniravichandran commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItWlsSamples.java
> +  public void testNginxIngressController() {
Remove public

2021-12-14 21:16 UTC, robertpatrick commented
What is the status of this PR? It is over 4 months old so is it still relevant? If so, then update the PR to make it so that it can be merged with current code. Otherwise, please close it.

2021-12-15 23:29 UTC, closed without merging