Remove voyager usecases from Integration Tests
oracle/weblogic-kubernetes-operator pull request #2559
Opened 2021-10-04 14:07 UTC by anpanigr

Removed all the Voyager Integration tests  from Operator Integration tests. 

External Jenkin Run

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/6598/

2021-10-04 15:22 UTC, maggiehe00 requested changes
The change should be OK on OKD but verifying the change on OKD wko-okd-wls-cert profile would be safer especially for ItManagedCoherence.

2021-10-05 14:53 UTC, maggiehe00 approved these changes
wko-okd run is good :)

2021-10-05 17:30 UTC, vanajamukkara approved these changes
LGTM

2021-10-05 17:30 UTC, vanajamukkara commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItManagedCoherence.java
> +      // clusterNameMsPortMap.put(clusterName, managedServerPort);
remove commented code

2021-10-05 23:31 UTC, merged