Created Utility methods for creating Yaml file with DOMAINUID param on fly
oracle/weblogic-kubernetes-operator pull request #2716
Opened 2022-01-14 13:50 UTC by hzhao-github

created util methods in CommonTestUtils.java to be used by ItIstioGatewaySessionMigration.java, ItIstioSessionMigration.java, ItMonitoringExporterSideCar.java and ItSessionMigration.java

2022-01-14 20:39 UTC, marinakog approved these changes

2022-01-14 20:40 UTC, marinakog commented
Could you please post results of jenkin job?

2022-01-14 20:41 UTC, marinakog requested changes
please provide Jenkins job results

2022-01-19 01:28 UTC, anpanigr approved these changes

2022-01-19 19:38 UTC, marinakog approved these changes

2022-01-19 19:38 UTC, merged