Added Istio SessionMigration tests to Release 3.3 and created util methods
oracle/weblogic-kubernetes-operator pull request #2789
Opened 2022-02-17 22:50 UTC by hzhao-github

Jenkins jobs:

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8863
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8865

With latest changes

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8883
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8885

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/8913

2022-02-23 18:05 UTC, xiancao requested changes

2022-02-23 18:05 UTC, xiancao commented on integration-tests/src/test/resources/istio/istio-sessmigr-template.yaml
> +# Copyright (c) 2021, Oracle and/or its affiliates.
change this copyright to:
// Copyright (c) 2022, Oracle and/or its affiliates.

2022-02-23 19:42 UTC, hzhao-github commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioGatewaySessionMigration.java
> +// Copyright (c) 2021, 2022, Oracle and/or its affiliates.
changed

2022-02-23 19:42 UTC, hzhao-github commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioSessionMigration.java
> +// Copyright (c) 2021, 2022, Oracle and/or its affiliates.
changed

2022-02-23 19:42 UTC, hzhao-github commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItIstioSessionMigration.java
> +    //final List<String> modelList = Collections.singletonList(MODEL_DIR + "/" + SESSMIGR_MODEL_FILE);
removed

2022-02-23 19:42 UTC, hzhao-github commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMonitoringExporter.java
> +    //String miiImage1 = createAndVerifyMiiImage(MODEL_DIR + "/model.sessmigr.yaml");
removed

2022-02-23 19:42 UTC, hzhao-github commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMonitoringExporter.java
> +    //"\"domain\":\"wls-sessmigr-domain-1\"");
removed

2022-02-24 19:55 UTC, anpanigr approved these changes

2022-02-28 17:24 UTC, xiancao approved these changes

2022-02-28 18:41 UTC, merged