fixed duplicated domainuid
oracle/weblogic-kubernetes-operator pull request #2883
Opened 2022-03-30 20:16 UTC by marinakog

2022-03-30 20:18 UTC, marinakog commented
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9502

2022-03-30 20:21 UTC, anpanigr approved these changes

2022-03-30 20:31 UTC, vanajamukkara approved these changes

2022-03-30 20:42 UTC, vanajamukkara commented
pls run the entire parallel suite

2022-03-31 03:58 UTC, sankarpn requested changes
Please revert back the ItKubernetesEvents tests are before.

2022-03-31 03:58 UTC, sankarpn commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesEvents.java
> +    checkNamespaceWatchingStoppedEvent(opNamespace, domainNamespace2, domainUid, "Normal", timestamp,
domainUid should be null as before. NamespaceWatchingStopped event will not contin domainUID

2022-03-31 03:58 UTC, sankarpn commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesEvents.java
> +    checkNamespaceWatchingStoppedEvent(opNamespace, domainNamespace3, domainUid, "Normal", timestamp,
domainUid should be null as before. NamespaceWatchingStopped event will not contin domainUID

2022-03-31 03:58 UTC, sankarpn commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesEvents.java
> +    checkNamespaceWatchingStoppedEvent(opNamespace, domainNamespace5, domainUid, "Normal", timestamp,
domainUid should be null as before. NamespaceWatchingStopped event will not contin domainUID

2022-03-31 03:58 UTC, sankarpn commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItKubernetesEvents.java
> +    checkNamespaceWatchingStoppedEvent(opNamespace, domainNamespace4, domainUid, "Normal", timestamp, false);
domainUid should be null as before. NamespaceWatchingStopped event will not contin domainUID

2022-03-31 03:59 UTC, sankarpn reviewed
fix typo

2022-03-31 04:08 UTC, sankarpn approved these changes
lgtm

2022-03-31 13:35 UTC, vanajamukkara reviewed
There are failures in ItKubernetesEvents class in the results posted in the PR. I don't see those failures in nightly run https://build.weblogick8s.org:8443/job/wko-kind-nightly-parallel/830/. Are these intermittent? Is there a JIRA to track these failures?

2022-03-31 15:38 UTC, marinakog commented
> There are failures in ItKubernetesEvents class in the results posted in the PR. I don't see those failures in nightly run https://build.weblogick8s.org:8443/job/wko-kind-nightly-parallel/830/. Are these intermittent? Is there a JIRA to track these failures?

Hi Vanaja, it was older runs, I have updated with newest results.

2022-03-31 18:24 UTC, anpanigr approved these changes
lgtm

2022-04-01 14:29 UTC, vanajamukkara approved these changes

2022-04-01 14:54 UTC, merged