Enable wls-srg profile and removed test method ordering in few ItClasses
oracle/weblogic-kubernetes-operator pull request #2884
Opened 2022-03-30 21:34 UTC by anpanigr

This PR covers following changes 
  a) modify kindtest.sh to run  wls-srg profile
  b) Merged tests methods to remove test dependencies in the following classes  
         ItDedicatedMode, ItIstioDomainInImage and ItLivenessProbeCustomization

Jenkin Run ( in progress) 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9522/  ( Kind-parallel) 
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/9523   (Kind-sequential)

2022-03-31 22:38 UTC, hzhao-github commented
LGTM

2022-04-01 15:17 UTC, vanajamukkara commented
Wait on this, please don't merge....

2022-04-01 15:18 UTC, vanajamukkara requested changes
discussing few more changes

2022-04-06 22:02 UTC, vanajamukkara approved these changes

2022-04-06 23:32 UTC, merged