OKD specific changes to integration tests in release/3.3
oracle/weblogic-kubernetes-operator pull request #2919
Opened 2022-04-06 17:28 UTC by sankarpn

release/3.3 integration tests was not supporting OKD platform. These changes are made to run the integration tests in release/3.3 to run on OKD platform.

2022-04-06 19:46 UTC, rjeberhard approved these changes
Approved, but you need to merge conflicts with latest changes.

2022-04-07 01:33 UTC, xiancao requested changes

2022-04-07 01:33 UTC, xiancao commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/actions/impl/primitive/WitParams.java
> +  // Custom WDT model home
delete or change this comment line

2022-04-07 01:33 UTC, xiancao commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/assertions/impl/Domain.java
> +    //final HtmlPage loginPage = assertDoesNotThrow(() -> webClient.getPage(consoleUrl),
delete this commented out line

2022-04-07 01:33 UTC, xiancao commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/DomainUtils.java
> +                                  .mountPath("/u01/weblogic"), // availble under /u01/weblogic inside pod
.name() and .mountPath() should be in the same level, reformat it

2022-04-07 01:33 UTC, xiancao commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/FmwUtils.java
> +   * @param domainNamespace  namespace where the domain exists
The parameter order is wrong. domainNamespace should be the first one.

2022-04-07 01:33 UTC, xiancao commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PersistentVolumeUtils.java
> +      pvHostPath = Files.createDirectories(Paths.get(PV_ROOT, className, pvName));
use static import Files.createDirectories and Paths.get here

2022-04-07 01:33 UTC, xiancao commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/PersistentVolumeUtils.java
> +
delete empty line

2022-04-12 15:05 UTC, maggiehe00 approved these changes
I'm approving this PR since I know all the single test passed on another OKD cluster. Let's get it merge and we can fix/improve later.

2022-04-21 18:47 UTC, rjeberhard commented
Closing `release/3.3` PR's.

2022-04-21 18:47 UTC, closed without merging