OWLS-99201 - run tests only against certified versions for Grafana and Prometheus, removed test against latest versions
oracle/weblogic-kubernetes-operator pull request #3063
Opened 2022-05-12 15:19 UTC by marinakog

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/10622

2022-05-12 16:13 UTC, anpanigr reviewed
The failures reported on the jenkin runs has been resolved.  Can you sync to the main and rerun the tests

2022-05-13 03:35 UTC, anpanigr approved these changes
lgtm

2022-05-13 14:50 UTC, sankarpn requested changes

2022-05-13 14:50 UTC, sankarpn commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/MonitoringUtils.java
> +    assertThat(callWebAppAndCheckForServerNameInResponse(curlCmd, managedServerNames, 100))
Instead of simply increasing the iteration can we use the testUntil to wait for the required response?

2022-05-13 15:20 UTC, hzhao-github approved these changes

2022-05-16 17:30 UTC, sankarpn commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/MonitoringUtils.java
> +    assertThat(callWebAppAndCheckForServerNameInResponse(curlCmd, managedServerNames, 100))
Please remove the commented code.

2022-05-16 17:31 UTC, sankarpn approved these changes
lgtm

2022-05-16 20:20 UTC, merged