Operator upgrade (from v8) with Istio Enabled domain
oracle/weblogic-kubernetes-operator pull request #3255
Opened 2022-07-15 20:56 UTC by anpanigr

The PR covers the following change

(a) Refactor the code to add a UpgradeUtil/IstioUtil class to be used in any Operator Version Upgrade scenario.
(b) Add a new Integration test class to ((i) create Domain Resource with Istio using a checked-in domain.yaml (ii) upgrade the domain to main and see if the web request still routes thru istio ingress port.

https://build.weblogick8s.org:8443/job/wko-kind-nightly-seqential/739 (entire sequential run) 
https://build.weblogick8s.org:8443/job/wko-kind-nightly-seqential/743 (entire sequential run) 
https://build.weblogick8s.org:8443/job/wko-kind-nightly-seqential/745/  (entire sequential run) 
https://build.weblogick8s.org:8443/job/wko-oke-nightly-seqential/29/

2022-07-15 21:44 UTC, marinakog requested changes
please run oke-sequential Jenkins job against your change. ( in the configuration switch to your branch name, provide **/testnameclass for IT_NAME

2022-07-15 21:44 UTC, marinakog commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorIstioUpgrade.java
> +    logger.info("Verifying Istio Service @IngressPort [{0}]", istioIngressPort);
typo : Administration

2022-07-19 18:35 UTC, sankarpn requested changes

2022-07-19 20:01 UTC, anpanigr commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorIstioUpgrade.java
> + * Make sure the console is acessible thru istio ingress port
done

2022-07-19 20:01 UTC, anpanigr commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorIstioUpgrade.java
> +  public static void init() {
done

2022-07-19 20:01 UTC, anpanigr commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorIstioUpgrade.java
> +   * Istio Domain upgrade from Operator v3.4.1 to current.
done

2022-07-19 20:02 UTC, anpanigr commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorIstioUpgrade.java
> +  public static final String OLD_DOMAIN_VERSION = "v8";
done

2022-07-19 20:09 UTC, anpanigr commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItOperatorIstioUpgrade.java
> +      CleanupUtil.cleanup(namespaces);
done

2022-07-19 22:57 UTC, marinakog approved these changes

2022-07-20 21:39 UTC, vanajamukkara approved these changes

2022-07-20 23:27 UTC, sankarpn approved these changes
lgtm

2022-07-21 16:55 UTC, merged