WKO 4.0: Update ItIstioGatewaySessionMigration,ItIstioManagedCoherence,ItIstioSessionMigration, ItDedicatedMode to V9 ClusterResource
oracle/weblogic-kubernetes-operator pull request #3364
Opened 2022-08-26 18:06 UTC by xiancao

WKO 4.0: Update ItIstioGatewaySessionMigration,ItIstioManagedCoherence,ItIstioSessionMigration, ItDedicatedMode to V9 ClusterResource

Jenkins result:
https://build.weblogick8s.org:8443/view/all/job/weblogic-kubernetes-operator-kind-new/12482/

2022-08-26 19:16 UTC, anpanigr approved these changes
lgtm

2022-08-30 03:41 UTC, sankarpn requested changes
minor comments

2022-08-30 03:41 UTC, sankarpn commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ClusterUtils.java
>      assertNotNull(cluster, "cluster is null");
This is not going to fail, if cluster is null line # 70 will throw NPE
You can move line 70 and 71 below these null checks

2022-08-30 03:41 UTC, sankarpn commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/utils/ClusterUtils.java
> +            clusterResourceName, namespace));
If createClusterCustomResource returns false then there is no ApiException was thrown then this assert message will be misleading.

2022-08-30 17:08 UTC, sankarpn approved these changes
lgtm

2022-08-30 20:59 UTC, merged