Add a usecase to create multiple domains/clusters and lifecycle tests
oracle/weblogic-kubernetes-operator pull request #3464
Opened 2022-09-28 15:48 UTC by sankarpn

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13214/
https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/13213/

2022-09-28 19:06 UTC, xiancao requested changes

2022-09-29 15:59 UTC, sankarpn commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLargeCapacityDomainsClusters.java
> +  private static final ConditionFactory withStandardRetryPolicy
fixed

2022-09-29 16:00 UTC, sankarpn commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLargeCapacityDomainsClusters.java
> +        ItIntrospectVersion.class.getName() + "/clusterviewapp");
fixed

2022-09-29 16:03 UTC, sankarpn commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLargeCapacityDomainsClusters.java
> +      shutdownDomain(domainUid, domainNamespaces.get(i));
fixed. commented the shutdown call

2022-09-29 18:51 UTC, xiancao approved these changes
minor comments

2022-09-29 18:51 UTC, xiancao commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLargeCapacityDomainsClusters.java
> +      //shutdownDomain(domainUid, domainNamespaces.get(i));
delete the commented out line

2022-09-29 18:51 UTC, xiancao commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItLargeCapacityDomainsClusters.java
> +   * c. Verifies the servers in the new WebLogic domain comes up.
Verifies the servers in the new WebLogic domain comes up. -> Verifies the servers in the new WebLogic domain come up.

2022-09-29 19:11 UTC, anpanigr approved these changes

2022-09-29 21:15 UTC, merged