OWLS-103358, OWLS-106012 - fixed intermittent failures and adapted wdt3.0 changes
oracle/weblogic-kubernetes-operator pull request #3861
Opened 2023-01-18 23:50 UTC by marinakog

https://build.weblogick8s.org:8443/job/weblogic-kubernetes-operator-kind-new/15764

2023-01-19 16:33 UTC, anpanigr commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java
> +   * Verify domain events and operator log contains the expected error message.
Provide the description of expected message  (createDomain argument processing failed: createDomain failed to find a model file)

2023-01-19 17:39 UTC, xiancao requested changes

2023-01-19 17:39 UTC, xiancao commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java
> +      + " files dir in the auxiliary image")
can you combines these two lines into one?

2023-01-19 17:39 UTC, xiancao commented on integration-tests/src/test/java/oracle/weblogic/kubernetes/ItMiiAuxiliaryImage.java
> +        "configmap {0} to be deleted.");
You need to add configmap here.
testUntil(
         withLongRetryPolicy,
         () -> listConfigMaps(domainNamespace).getItems().stream().noneMatch((cm)
             -> (cm.getMetadata().getName().equals(configMapName))),
         logger,
         "configmap {0} to be deleted",
         configMapName);

2023-01-19 18:17 UTC, anpanigr reviewed
Make sure all changes are backported into release/4.0 and release/3/.4

2023-01-20 19:00 UTC, xiancao approved these changes

2023-01-20 22:32 UTC, merged